module:
  admin_toolbar: 0
  admin_toolbar_links_access_filter: 0
  admin_toolbar_tools: 0
  big_pipe: 0
  blazy: 0
  blazy_ui: 0
  block: 0
  bootstrap_layouts: 0
  breakpoint: 0
  captcha: 0
  ckeditor: 0
  config: 0
  contextual: 0
  crop: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity_browser: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_mdm: 0
  filter: 0
  google_tag: 0
  help: 0
  honeypot: 0
  image: 0
  image_widget_crop: 0
  imagemagick: 0
  layout_builder: 0
  layout_discovery: 0
  link: 0
  media: 0
  media_library: 0
  memcache: 0
  memcache_admin: 0
  menu_link_content: 0
  menu_ui: 0
  metatag: 0
  mysql: 0
  node: 0
  options: 0
  page_cache: 0
  password_policy: 0
  password_policy_character_types: 0
  password_policy_characters: 0
  password_policy_history: 0
  password_policy_length: 0
  password_policy_username: 0
  path: 0
  path_alias: 0
  rdf: 0
  recaptcha: 0
  seckit: 0
  security_review: 0
  smtp: 0
  sophron: 0
  system: 0
  taxonomy: 0
  text: 0
  token: 0
  toolbar: 0
  update: 0
  user: 0
  username_enumeration_prevention: 0
  video_embed_field: 0
  video_embed_media: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  pathauto: 1
  views: 10
  paragraphs: 11
  opencommunications: 1000
theme:
  stark: 0
  bartik: 0
profile: opencommunications
_core:
  default_config_hash: R4IF-ClDHXxblLcG0L7MgsLvfBIMAvi_skumNFQwkDc
